nomenclature:
  name: no_dues
  verboseName: No dues
description: An app for Omniport that does what apps do
baseUrls:
  http: no_dues/
  static: no_dues/
isApi: true
acceptables:
  roles:
  - name: no_dues.Subscriber
  - name: no_dues.Verifier
