nomenclature:
  name: no_dues
  verboseName: No dues
description: Get your green card digitally without any red light
baseUrls:
  http: no_dues/
  static: no_dues/
isApi: true
acceptables:
  roles:
  - name: no_dues.Subscriber
    activeStatuses:
    - IS_ACTIVE
    - HAS_BEEN_ACTIVE
  - name: no_dues.Verifier
