# Generated by Django 2.2.6 on 2020-04-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_dues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='residence_selected',
            field=models.BooleanField(default=False),
        ),
    ]
