# Generated by Django 2.2.6 on 2020-04-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('no_dues', '0002_subscriber_residence_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='residence_selected',
            new_name='required_authorities_selected',
        ),
    ]
