# Generated by Django 2.2.6 on 2020-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_dues', '0003_auto_20200425_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
