# Generated by Django 3.0.3 on 2020-04-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_dues', '0004_permission_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
